version: '3.9'

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_DATABASE=flask_login